<a href="https://colab.research.google.com/github/URK23CS1219/Experiment/blob/main/knn_workbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Machine Learning Algorithm

In machine learning, there are three types:

1. **Supervised Learning**:  the model is trained on a labeled dataset, where each example is paired with the correct label.

2. **Unsupervised Learning**: In unsupervised learning, the model is given an unlabeled dataset and must find patterns and relationships

3. **Reinforcement Learning**: The model receives feedback in the form of rewards or penalties based on its actions and learns to maximize its reward over time.

### Supervised Learning

Under supervised learning, there are two main types:

1. **Classification**
2. **Regression**



##IMPORTING

train_test_split - splits a dataset into two subsets:

1). one for training a model

2). another for testing the model.

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [2]:
df=pd.read_csv('diabetes.csv',index_col=0)
df.head()

City  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  \
Name                                                                            
Ann        Kovai            6      148             72             35        0   
Sam       Trichy            1       85             66             29        0   
George   Madurai            8      183             64              0        0   
Sam     Banglore            1       89             66             23       94   
Matt    Banglore            0      137             40             35      168   

         BMI  DiabetesPedigreeFunction  Age Outcome  
Name                                                 
Ann     33.6                     0.627   50     Yes  
Sam     26.6                     0.351   31      No  
George  23.3                     0.672   32     Yes  
Sam     28.1                     0.167   21      No  
Matt    43.1                     2.288   33     Yes

Data Cleaning

In [3]:
cols = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols] = df[cols].replace(0, np.nan)
df.head(10)

City  Pregnancies  Glucose  BloodPressure  SkinThickness  \
Name                                                                     
Ann          Kovai            6    148.0           72.0           35.0   
Sam         Trichy            1     85.0           66.0           29.0   
George     Madurai            8    183.0           64.0            NaN   
Sam       Banglore            1     89.0           66.0           23.0   
Matt      Banglore            0    137.0           40.0           35.0   
Matt      Banglore            5    116.0           74.0            NaN   
Matt       Chennai            3     78.0           50.0           32.0   
George       Kovai           10    115.0            NaN            NaN   
Jennifer  Banglore            2    197.0           70.0           45.0   
Jennifer    Trichy            8    125.0           96.0            NaN   

          Insulin   BMI  DiabetesPedigreeFunction  Age Outcome  
Name                                                            
Ann           NaN  33.6                     0.627   50     Yes  
Sam           NaN  26.6                     0.351   31      No  
George        NaN  23.3                     0.672   32     Yes  
Sam          94.0  28.1                     0.167   21      No  
Matt        168.0  43.1                     2.288   33     Yes  
Matt          NaN  25.6                     0.201   30      No  
Matt         88.0  31.0                     0.248   26     Yes  
George        NaN  35.3                     0.134   29      No  
Jennifer    543.0  30.5                     0.158   53     Yes  
Jennifer      NaN   NaN                     0.232   54     Yes

In [4]:
df.shape

(768, 10)

In [5]:
df.isnull().sum()

City                          0
Pregnancies                   0
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [6]:
df.fillna(df.mean(),inplace=True)
df.head()

<ipython-input-6-918818d888db>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.mean(),inplace=True)


City  Pregnancies  Glucose  BloodPressure  SkinThickness  \
Name                                                                   
Ann        Kovai            6    148.0           72.0       35.00000   
Sam       Trichy            1     85.0           66.0       29.00000   
George   Madurai            8    183.0           64.0       29.15342   
Sam     Banglore            1     89.0           66.0       23.00000   
Matt    Banglore            0    137.0           40.0       35.00000   

           Insulin   BMI  DiabetesPedigreeFunction  Age Outcome  
Name                                                             
Ann     155.548223  33.6                     0.627   50     Yes  
Sam     155.548223  26.6                     0.351   31      No  
George  155.548223  23.3                     0.672   32     Yes  
Sam      94.000000  28.1                     0.167   21      No  
Matt    168.000000  43.1                     2.288   33     Yes

In [7]:
df.isnull().sum()

City                        0
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

Take x as independent variable

In [8]:
X= df[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness','Insulin','BMI', 'DiabetesPedigreeFunction', 'Age']]
X

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin  \
Name                                                                       
Ann                 6    148.0           72.0       35.00000  155.548223   
Sam                 1     85.0           66.0       29.00000  155.548223   
George              8    183.0           64.0       29.15342  155.548223   
Sam                 1     89.0           66.0       23.00000   94.000000   
Matt                0    137.0           40.0       35.00000  168.000000   
...               ...      ...            ...            ...         ...   
Matt               10    101.0           76.0       48.00000  180.000000   
Matt                2    122.0           70.0       27.00000  155.548223   
Jennifer            5    121.0           72.0       23.00000  112.000000   
Matt                1    126.0           60.0       29.15342  155.548223   
Ann                 1     93.0           70.0       31.00000  155.548223   

           BMI  DiabetesPedigreeFunction  Age  
Name                                           
Ann       33.6                     0.627   50  
Sam       26.6                     0.351   31  
George    23.3                     0.672   32  
Sam       28.1                     0.167   21  
Matt      43.1                     2.288   33  
...        ...                       ...  ...  
Matt      32.9                     0.171   63  
Matt      36.8                     0.340   27  
Jennifer  26.2                     0.245   30  
Matt      30.1                     0.349   47  
Ann       30.4                     0.315   23  

[768 rows x 8 columns]

Take y as dependent Variable

In [9]:
y=df[['Outcome']]
y

Outcome
Name            
Ann          Yes
Sam           No
George       Yes
Sam           No
Matt         Yes
...          ...
Matt          No
Matt          No
Jennifer      No
Matt         Yes
Ann           No

[768 rows x 1 columns]

In [10]:
y = y.replace({'No': 0, 'Yes': 1})
y

Outcome
Name             
Ann             1
Sam             0
George          1
Sam             0
Matt            1
...           ...
Matt            0
Matt            0
Jennifer        0
Matt            1
Ann             0

[768 rows x 1 columns]

In [11]:
df.shape

(768, 10)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25,random_state=42)
X_train

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin  \
Name                                                                       
George             13    129.0      72.405184       30.00000  155.548223   
Ann                 4    129.0      86.000000       20.00000  270.000000   
Jennifer            3     61.0      82.000000       28.00000  155.548223   
Matt                2     81.0      72.000000       15.00000   76.000000   
Sam                 0    102.0      75.000000       23.00000  155.548223   
...               ...      ...            ...            ...         ...   
Ann                 5    139.0      64.000000       35.00000  140.000000   
Matt                1     96.0     122.000000       29.15342  155.548223   
Jennifer           10    101.0      86.000000       37.00000  155.548223   
Jennifer            0    141.0      72.405184       29.15342  155.548223   
Jennifer            0    125.0      96.000000       29.15342  155.548223   

                BMI  DiabetesPedigreeFunction  Age  
Name                                                
George    39.900000                     0.569   44  
Ann       35.100000                     0.231   23  
Jennifer  34.400000                     0.243   46  
Matt      30.100000                     0.547   25  
Sam       32.457464                     0.572   21  
...             ...                       ...  ...  
Ann       28.600000                     0.411   26  
Matt      22.400000                     0.207   27  
Jennifer  45.600000                     1.136   38  
Jennifer  42.400000                     0.205   29  
Jennifer  22.500000                     0.262   21  

[576 rows x 8 columns]

In [13]:

X_test

Pregnancies  Glucose  BloodPressure  SkinThickness     Insulin  \
Name                                                                       
Jennifer            6     98.0           58.0       33.00000  190.000000   
Ann                 2    112.0           75.0       32.00000  155.548223   
George              2    108.0           64.0       29.15342  155.548223   
Sam                 8    107.0           80.0       29.15342  155.548223   
Jennifer            7    136.0           90.0       29.15342  155.548223   
...               ...      ...            ...            ...         ...   
Matt                1     84.0           64.0       23.00000  115.000000   
Sam                 6    194.0           78.0       29.15342  155.548223   
Matt                6    123.0           72.0       45.00000  230.000000   
Matt                3     78.0           50.0       32.00000   88.000000   
Sam                 3    106.0           72.0       29.15342  155.548223   

           BMI  DiabetesPedigreeFunction  Age  
Name                                           
Jennifer  34.0                     0.430   43  
Ann       35.7                     0.148   21  
George    30.8                     0.158   21  
Sam       24.6                     0.856   34  
Jennifer  29.9                     0.210   50  
...        ...                       ...  ...  
Matt      36.9                     0.471   28  
Sam       23.5                     0.129   59  
Matt      33.6                     0.733   34  
Matt      31.0                     0.248   26  
Sam       25.8                     0.207   27  

[192 rows x 8 columns]

In [14]:
y_train

Outcome
Name             
George          1
Ann             0
Jennifer        0
Matt            0
Sam             0
...           ...
Ann             0
Matt            0
Jennifer        1
Jennifer        1
Jennifer        0

[576 rows x 1 columns]

In [15]:
y_test

Outcome
Name             
Jennifer        0
Ann             0
George          0
Sam             0
Jennifer        0
...           ...
Matt            0
Sam             1
Matt            0
Matt            1
Sam             0

[192 rows x 1 columns]

KNN calling

trains the KNN classifier on the training data

In [16]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

Using trained KNN classifier to make predictions on the test data

In [17]:
y_pred = knn.predict(X_test)

In [18]:
 print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
 print("Accuracy:", accuracy_score(y_test, y_pred))
 #print("Classification Report:\n", classification_report(y_test, y_pred))


Confusion Matrix:
 [[87 36]
 [29 40]]
Accuracy: 0.6614583333333334


In [19]:
for i in [5,7,9,11]:
  knn = KNeighborsClassifier(n_neighbors=i)
  knn.fit(X_train,y_train)
  y_pred = knn.predict(X_test)
  print("ConfusionMatrix:\n",confusion_matrix(y_test,y_pred))
  print("Accuracy:",accuracy_score(y_test,y_pred))
#  print("ClassificationReport:\n",classification_report(y_test,y_pred))

ConfusionMatrix:
 [[83 40]
 [28 41]]
Accuracy: 0.6458333333333334
ConfusionMatrix:
 [[85 38]
 [28 41]]
Accuracy: 0.65625
ConfusionMatrix:
 [[90 33]
 [27 42]]
Accuracy: 0.6875
ConfusionMatrix:
 [[90 33]
 [28 41]]
Accuracy: 0.6822916666666666


/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for 